# Generated by Django 4.0.4 on 2022-04-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='time_limit_mins',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='count',
            field=models.IntegerField(default=15),
        ),
    ]
