# Generated by Django 3.1.4 on 2022-04-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_module_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='video',
        ),
    ]
