# Generated by Django 3.1.4 on 2022-04-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=100)),
                ('meeting_url', models.URLField(max_length=2000)),
                ('start_time', models.TimeField(default='12:00:0')),
                ('end_time', models.TimeField(default='12:00:0')),
                ('mondey', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
            ],
        ),
    ]
