# Generated by Django 3.1.4 on 2022-04-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_course_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.CharField(default=0, max_length=55),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
